bmicalc/urls.py
from django.urls import path
from .views import MainView

app_name = 'bmicalc'

urlpatterns = [
    path('', MainView, name='index'),
]

diet/urls.py
from django.urls import path
from . import views

app_name = 'diet'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('<int:diet_id>/', views.detailView, name='detail'),
    path('submit_review/<int:diet_id>/', views.submit_review, name='submit_review'),
]

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('add/', views.CreatePost.as_view(), name='add'),
    path('like/', views.like_comment, name='like'),
    path('<slug:slug>/delete/', views.DeletePost.as_view(), name='delete'),
    path('<slug:slug>/', views.DetailView.as_view(), name='detail'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.homeView, name='index'),
]

login/urls.py
from django.urls import path
from . import views


app_name = 'login'

urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('profile/<slug:slug>/', views.profilePage, name='profile'),

] 

training/urls.py
from django.urls import path
from . import views

app_name = 'training'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('<int:training_id>/', views.detailView, name='detail'),
    path('submit_review/<int:training_id>/', views.submit_review, name='submit_review'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("home.urls")),
    path('diet/', include("diet.urls")),
    path('admin/', admin.site.urls),
    path('account/', include("login.urls")),
    path('training/', include("training.urls")),
    path('forum/', include("forum.urls")),
    path('bmicalc/', include("bmicalc.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from diet.models import Diet, Review
from training.models import Training, TrainingReview
from forum.models import Post, Comment

def homeView(request):
    review1 = Review.objects.all().order_by('-date').first()
    review2 = TrainingReview.objects.all().order_by('-date').first()

    diets = Diet.objects.all()
    maxcount_diets = 0
    for diet in diets:
        reviews_diet = Review.objects.filter(object=diet).count()
        if(maxcount_diets<reviews_diet):
            maxcount_diets = reviews_diet
            max_diet = diet

    trainings = Training.objects.all()
    maxcount_training = 0
    for training in trainings:
        reviews_training = TrainingReview.objects.filter(object=training).count()
        if(maxcount_training<reviews_training):
            maxcount_training = reviews_training
            max_training = training

    posts = Post.objects.all()
    maxcount_post = 0
    for post in posts:
        reviews_post = Comment.objects.filter(post=post).count()
        if(maxcount_post<reviews_post):
            maxcount_post = reviews_post
            max_post = post

    context = {
        'diet': max_diet,
        'training': max_training,
        'post': max_post,
        'review_diet': review1,
        'review_training': review2,
    }
    return render(request, 'home/index.html', context)

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Strenghening</title>

    {% load static %}
    <!-- Bootstrap and JQuery -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Our project just needs Font Awesome Free's Solid and Brand files -->
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'home/style.css' %}" rel="stylesheet" >
    {% block head %}

    {% endblock %}
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark p-md-3">
        <a class="navbar-brand" href="{% url 'home:index' %}">
            <i class="fa-solid fa-dumbbell"></i>&nbsp; Strenghening
        </a>
        <!--Navbar toggler button-->
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
        <span class="navbar-toggler-icon"></span>
        </button>

        <!--Elements of navbar-->
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="mx-auto"></div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'home:index' %}">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'forum:index' %}">FORUM</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'diet:index' %}">DIET</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'training:index' %}">TRAINING</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'bmicalc:index' %}">BMI CALKULATOR</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'login:profile' user.profile.slug %}">
                                <img
                                    src="{{ user.profile.image.url }}"
                                    class="rounded-circle"
                                    height="25"
                                    alt="Black and White Portrait of a Man"
                                    loading="lazy"
                                />
                                {{request.user}}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'login:logout' %}">
                                <i class="fa-solid fa-power-off"></i>&nbsp; LOGOUT &nbsp;
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'login:login' %}" class="nav-link text-white" tabindex="-1" role="button" aria-disabled="true">SIGN IN</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block body %}

    {% endblock %}

    <section class="footer">
        <h1>Projekt strony wykonany na potrzeby projektu z IT
          <br>
          © COPYRIGHT Szymon Abramik, Remigiusz Abramik 2022-2023r.
        </h1>
    </section>

    <script type="text/javascript">
        var nav = document.querySelector('nav');
        
        window.addEventListener('scroll', function () {
            if (window.pageYOffset > 50) {
            nav.classList.add('nav-black', 'shadow');
            } else {
            nav.classList.remove('nav-black', 'shadow');
            }
        });
    </script>      
</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}

{% block head %}
    {% load static %}
    <link href="{% static 'home/style_index.css' %}" rel="stylesheet" >
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
{% endblock %}

{% block body %}
  <!-- Banner Image  -->
  <div class="banner-image w-100 vh-100 d-flex justify-content-center align-items-center"></div>
  <div class="row row-1">
    <div class="main-page-photo"></div>
    <div class="text-box">
      <h1>ODKRYWAJ NOWE HORYZONTY Z NASZĄ WITRYNĄ</h1>
      <p>Et sapiente dolores qui repudiandae tempora et ullam dolor est distinctio repudiandae sit quaerat natus qui ipsa voluptatum est iure vitae. 
      <br>Et aliquid nobis est quam autem aut minima dolorem! Ad doloribus voluptate qui neque voluptatibus est recusandae sint. Qui dolor obcaecati sed rerum eligendi 
      <br>et quibusdam asperiores eum placeat cupiditate id sint optio ab corrupti voluptatem.</p>
      <div class="hero-btn">
        <a href="{% url 'login:register'%}">Dołącz do nas już dziś</a>
      </div>
    </div>
  </div>
<section class="widgets">
  <h1>Nasza strona oferuje wiele możliwości</h1><br>
  <p>Et sapiente dolores qui repudiandae tempora et ullam dolor est distinctio repudiandae sit quaerat natus qui ipsa voluptatum est iure vitae. </p>
  <div class="row" style="margin-top:5%;">
    <div class="col">
      <img src="static/home/forum.png">
      <a href="{% url 'forum:index'%}">
        <div class="layer">
          <h3>FORUM</h3>
        </div>
      </a>
    </div>
    <div class="col">
      <img src="static/home/diet.png">
      <a href="{% url 'diet:index'%}">
        <div class="layer">
          <h3>DIET</h3>
        </div>
      </a>
    </div>
  </div>
  <div class="row" style="margin-top:5%;">
    <div class="col">
      <img src="static/home/training.png">
      <a href="{% url 'training:index'%}">
        <div class="layer">
          <h3>TRAINING</h3>
        </div>
      </a>
    </div>
    <div class="col">
      <img src="static/home/bmicalc.png">
      <a href="{% url 'bmicalc:index'%}">
        <div class="layer">
          <h3>BMI CALCULATOR</h3>
        </div>
      </a>
    </div>
  </div>
</section>
<section class="stats">
  <div class="row" style="margin-top:5%;">
    <div class="col-12 col-lg-5 stats-text-box">
      <h3>Troche do powiedzenia o naszej stronie!</h3>
      <p>Et sapiente dolores qui repudiandae tempora et ullam dolor est distinctio repudiandae sit quaerat natus qui ipsa voluptatum est iure vitae. 
      Et aliquid nobis est quam autem aut minima dolorem! Ad doloribus voluptate qui neque voluptatibus est recusandae sint. Qui dolor obcaecati sed rerum eligendi 
      et quibusdam asperiores eum placeat cupiditate id sint optio ab corrupti voluptatem.</p>
    </div>
    <div class="col-3 col-lg-2">
      <div class="type-row align-self-center"><h3>POST</h3></div>
      <div class="type-row"><h3>DIET</h3></div>
      <div class="type-row"><h3>TRAIN</h3></div>
    </div>
    <div class="col-9 col-lg-5">
      <div class="stats-row">
        <a href=""><h3>{{post.name}}</h3></a>
        <p class="fifty-chars">{{post.context}}</p>
        <p>Posted by <a href="">{{post.author}}</a> on {{post.start_date}}</p>
      </div>
      <div class="stats-row">
        <a href=""><h3>{{diet.name}}</h3></a>
        <p class="fifty-chars">{{diet.context}}</p>
        <p>Posted by <a href="">{{diet.author}}</a> on {{diet.date}}</p>
      </div>
      <div class="stats-row">
        <a href=""><h3>{{training.name}}</h3></a>
        <p class="fifty-chars">{{training.context}}</p>
        <p>Posted by <a href="">{{training.author}}</a> on {{training.date}}</p>
      </div>
    </div>
  </div>
</section>
<section class="comments">
  <h1>OPINIE</h1>
  <p>Pare kometarzy aby pokazać jak ludzie wyrażają sie o treściach na naszej stronie</p>
  <div class="row justify-content-center">
    <div class="col-12 col-lg-5 comment-section">
      <div class="row">
        <div class="col-3">
          <img src="{{ review_diet.author.image.url }}">
        </div>
        <div class="col-9">
          <div class="author-info row">
            <a href="">{{review_diet.author}}</a>&nbsp;
            {{review_diet.date}}
          </div>
          <div class="row">
            <span>
              <i class="fa fa-star{% if review_diet.rating == 0.5 %}-half-o{% elif review_diet.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review_diet.rating == 1.5 %}-half-o{% elif review_diet.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review_diet.rating == 2.5 %}-half-o{% elif review_diet.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review_diet.rating == 3.5 %}-half-o{% elif review_diet.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review_diet.rating == 4.5 %}-half-o{% elif review_diet.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
            </span>
          </div>
          <div class="row">
            <p>{{review_diet.context}}</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-5 comment-section">
      <div class="row">
        <div class="col-3">
          <img src="{{ review_training.author.image.url }}">
        </div>
        <div class="col-9">
          <div class="author-info row">
            <a href="">{{review_training.author}}</a>&nbsp;
            {{review_training.date}}
          </div>
          <div class="row">
            <span>
              <i class="fa fa-star{% if review_training.rating == 0.5 %}-half-o{% elif review_training.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review_training.rating == 1.5 %}-half-o{% elif review_training.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review_training.rating == 2.5 %}-half-o{% elif review_training.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review_training.rating == 3.5 %}-half-o{% elif review_training.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review_training.rating == 4.5 %}-half-o{% elif review_training.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
            </span>
          </div>
          <div class="row">
            <p>{{review_training.context}}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}