diet/urls.py
from django.urls import path
from . import views

app_name = 'diet'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('<int:diet_id>/', views.detailView, name='detail'),
    path('submit_review/<int:diet_id>/', views.submit_review, name='submit_review'),
]

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('add/', views.CreatePost.as_view(), name='add'),
    path('like/', views.like_comment, name='like'),
    path('<slug:slug>/delete/', views.DeletePost.as_view(), name='delete'),
    path('<slug:slug>/', views.DetailView.as_view(), name='detail'),
]

login/urls.py
from django.urls import path
from . import views


app_name = 'login'

urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('profile/<slug:slug>/', views.profilePage, name='profile'),

] 

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("home.urls")),
    path('diet/', include("diet.urls")),
    path('admin/', admin.site.urls),
    path('account/', include("login.urls")),
    path('training/', include("training.urls")),
    path('forum/', include("forum.urls")),
    path('bmicalc/', include("bmicalc.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from login.models import Profile
from django.contrib.auth.models import User
from django.utils.text import slugify

class Post(models.Model):
    name = models.CharField(max_length=100)
    context = models.TextField(max_length=1000)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    start_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    number = models.IntegerField(null=True)
    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("forum:detail", args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Comment(models.Model):
    context = models.TextField(max_length=1000)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    start_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments", null=True)
    likes = models.ManyToManyField(User, related_name='likes')
    
    @property
    def total_likes(self):
        return self.likes.all().count()
        _
    def __str__(self):
        return "| " + str(self.author) + " | " + " - " + " | " + str(self.post) + " | "


LIKE_CHOICES = {
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),

}
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, default='Like', max_length=10)

forum/forms.py
from django import forms
from .models import Post, Comment

class AddPost(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ('name', 'context')


class AddComment(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('context',)

forum/views.py
from django.views import generic
from .models import Post, Comment, Like
from .forms import AddPost, AddComment
from django.views.generic.edit import FormMixin
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.core.paginator import Paginator
from django.urls import reverse_lazy


def indexView(request): 
    p = Paginator(Post.objects.all().order_by('-start_date'), 4)
    page = request.GET.get('page')
    posts = p.get_page(page)
    context = {
        'posts': posts,
    }
    return render(request, 'forum/index.html', context)


class DetailView(FormMixin ,generic.DetailView):
    model = Post
    template_name = 'forum/detail.html'
    form_class = AddComment
    
    def get_success_url(self):
        return reverse('forum:detail', kwargs={'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['form'] = AddComment(initial={'post': self.object})
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.author = self.request.user.profile
        post = Post.objects.get(slug=self.object.slug)
        form.instance.post = post
        form.save()
        return super(DetailView, self).form_valid(form)

    def get_queryset(self):
        return super().get_queryset()
        

class DeletePost(generic.DeleteView):
    model = Post
    success_url = "/"
    

class CreatePost(generic.CreateView):
    model = Post
    form_class = AddPost
    template_name = 'forum/add.html'

    def form_valid(self, form):
        form.instance.author = self.request.user.profile
        return super().form_valid(form)


def like_comment(request):
    user = request.user
    if request.method == 'POST':
        comment_id = request.POST.get('comment_id')
        comment_obj = Comment.objects.get(id=comment_id)

        if user in comment_obj.likes.all():
            comment_obj.likes.remove(user)
        else:
            comment_obj.likes.add(user)

        like, created = Like.objects.get_or_create(user=user, comment_id=comment_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'

        like.save()

        data = {
            'value': like.value,
            'likes': comment_obj.likes.all().count()
        }

        return JsonResponse(data, safe=False)
    return HttpResponseRedirect("../{slug}/".format(slug=comment_obj.post.slug))

forum/templates/forum/add.html
{% extends 'home/base.html' %}

{% block head %}
    {% load static %}
    <link href="{% static 'forum/style_add.css' %}" rel="stylesheet" >
{% endblock %}

{% block body %}
<div class="padding-top"></div>
<div class="container-fluid">
        <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            <div class="form-title question-row center">
                <h1>Add Question</h1>
            </div>
            <div class="form-post-title question-row">
                <input type="text" name="name" class="form-control" placeholder="Question" maxlength="100" required="" id="id_name">
            </div>
            <div class="form-post-detail question-row">
                <textarea name="context" cols="40" rows="10" class="form-control" placeholder="Details of Question" maxlength="1000" required="" id="id_context"></textarea>
            </div>
            <div class="form-post-button question-row center">
                <button class="form-submit">Add Question</button>
            </div>
        </form>
    </div>
</div>
<div class="padding-bottom"></div>
{% endblock %}

forum/templates/forum/detail.html
{% extends 'home/base.html' %}

{% block head %}
    {% load static %}
    <link href="{% static 'forum/style_detail.css' %}" rel="stylesheet" >
{% endblock %}

{% block body %}
<div class="padding-top"></div>
<div class="container-fluid">
  <!-- HEAD POST -->
  <div class="row">
    <div class="col-lg-2 col-4">
      <div class="row justify-content-center"><img class="rounded-circle post-image" style="width: 140px; height: 140px" src="{{ object.author.image.url }}"></div>
    </div>
    <div class="col-lg-10 col-8">
      <div class="row">
        <h1>{{ object.name }}</h1>
      </div>
      <div class="row comment-stats">
        <p><a href="#">{{ object.author }}</a> - {{ object.start_date }}</p>
      </div>
      <div class="row">
        <p>{{ object.context }}</p>
      </div>
    </div>
  </div>
  <!-- ANSWEARS -->
  <div class="row">
    {% if not object.comments.all %}
    <div class="col"><div class="row justify-content-center border-top"><h3 style="padding:30px;"> No comments yet </h3></div></div>
    {% else %}
      <table class="table table-hover">
        <thead>
          <tr>
            <th style="width: 10%" scope="col"></th>
            <th style="width: 80%" scope="col">Answears</th>
            <th style="width: 10%" scope="col">Stats</th>
          </tr>
        </thead>
        <tbody>
          {% for comment in object.comments.all %}
            <tr>
              <td><img class="rounded-circle profile-picture" style="width: 100px; height: 100px" src="{{ comment.author.image.url }}"></td>
              <td><p class="comment-stats"><a href="{{ post.get_absolute_url }}">{{ comment.author }}</a> - {{ comment.start_date }}</p><p class="comment-content">{{ comment.context }}</p></td>
              <td>
                <div class="row auth">
                  <!-- LIKES FORM -->
                  <form action="{% url 'forum:like' %}" method="POST" style="display: inline-block;" id='{{comment.id}}' class="like-form">
                    {% csrf_token %}
                    <input type="hidden" name="comment_id" value="{{ comment.id }}">
                    {% if user.is_authenticated %} 
                      <button type="submit" class="comment-like like-btn{{comment.id}}">
                        {% if user not in comment.likes.all %}
                          Like
                        {% else %}
                          Unlike
                        {% endif %}
                      </button>
                    {% else %}
                      <a href="{% url 'login:login' %}">Login</a> to like
                    {% endif %}
                  </form>
                </div>
                <div class="row stats-likes" >
                  <p class="like-count{{comment.id}}"> {{comment.likes.all.count}} </p><p>&nbsp;-&nbsp;likes</p>
                </div>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endif %}
  </div>
  <!-- COMMENT FORM -->
  <div class="row justify-content-center">
    <form method="POST" action="">
      {% csrf_token %}
      <textarea name="context" cols="80" rows="5" maxlength="1000" required="" id="id_context" style="margin-top:20px; margin-bottom:20px;" required placeholder="Write your answear here!!"></textarea>
      <input type="hidden" name="post" value="6" id="id_post" style="margin-top:5px; margin-bottom:5px;">
      <div class="form-post-button">
          <button class="comment-like" type="submit">Add Question</button>
      </div>
    </form>
  </div>
</div>
<div class="padding-bottom"></div>

<script>
  $('.like-form').submit(function(e){
    e.preventDefault()
    const comment_id = $(this).attr('id')
    const likeText = $(`.like-btn${comment_id}`).text()
    const trim = $.trim(likeText)
    const url = $(this).attr('action')
    let res;
    const likes = $(`.like-count${comment_id}`).text()
    const trimCount = parseInt(likes)
    
    $.ajax({
        type: 'POST',
        url: url,
        data: {
            'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
            'comment_id':comment_id,
        },
        success: function(response) {
            if(trim === 'Unlike') {
                $(`.like-btn${comment_id}`).text('Like')
                res = trimCount - 1
            } else {
                $(`.like-btn${comment_id}`).text('Unlike')
                res = trimCount + 1
            }

            $(`.like-count${comment_id}`).text(res)
        },
        error: function(response) {
            console.log('error', response)
        }
    })

})
</script>

{% endblock %}

forum/templates/forum/index.html
{% extends 'home/base.html' %}

{% block head %}
    {% load static %}
    <link href="{% static 'forum/style.css' %}" rel="stylesheet" >
{% endblock %}
{% block body %}
<div class="padding-top"></div>
<div class="container-fluid">
    <div class="justify-content-center">
      <div class="text-center">
        <h1>FORUM</h1>
        <p>This is forum section where you can ask questions and help other people by answearing their question.
          {% if user.is_authenticated %} 
          If you wanna ask <a href="{% url 'forum:add' %}">clik here</a>.
          {% else %}
          If you wanna first you have to <a href="{% url 'login:login' %}">login</a>.
          {% endif %}
        </p>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">Question</th>
            <th scope="col">Activity</th>
            <th scope="col">Stats</th>
          </tr>
        </thead>
        <tbody>
          {% for post in posts %}
            <tr>
              <td><img class="rounded-circle profile-picture" src="{{ post.author.image.url }}"></td>
              <td><h5><a href="{{ post.get_absolute_url }}">{{ post.name }}</a></h5><p class="fifty-chars">{{ post.context }}</p></td>
              <td class="activity">{{ post.comments.all.count }}</td>
              <td>Posted by <a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a><br>{{ post.start_date }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <!-- PAGINATOR -->
      <nav aria-label="page-navigation">
        <ul class="pagination justify-content-center">
          {% if posts.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1"><span aria-hidden="true">&laquo;</span></a></li>
            <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}"><span aria-hidden="true">&lsaquo;</span></a></li>
          {% endif %}
        
          {% for i in posts.paginator.page_range %}
            <li class="{% if posts.number == i %}active {% endif %}page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
          {% endfor %}

          {% if posts.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}"><span aria-hidden="true">&rsaquo;</span></a></li>
            <li class="page-item"><a class="page-link" href="?page={{ posts.paginator.num_pages }}"><span aria-hidden="true">&raquo;</span></a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
</div>
<div class="padding-bottom"></div>
{% endblock %}