diet/urls.py
from django.urls import path
from . import views

app_name = 'diet'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('<int:diet_id>/', views.detailView, name='detail'),
    path('submit_review/<int:diet_id>/', views.submit_review, name='submit_review'),
]

login/urls.py
from django.urls import path
from . import views


app_name = 'login'

urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('profile/<slug:slug>/', views.profilePage, name='profile'),

] 

training/urls.py
from django.urls import path
from . import views

app_name = 'training'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('<int:training_id>/', views.detailView, name='detail'),
    path('submit_review/<int:training_id>/', views.submit_review, name='submit_review'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("home.urls")),
    path('diet/', include("diet.urls")),
    path('admin/', admin.site.urls),
    path('account/', include("login.urls")),
    path('training/', include("training.urls")),
    path('forum/', include("forum.urls")),
    path('bmicalc/', include("bmicalc.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

training/models.py
from django.db import models
from django.conf import settings
from login.models import Profile
from django.urls import reverse

class Training(models.Model):
    name = models.CharField(max_length=30)
    context = models.TextField(max_length=1000)
    image = models.ImageField(default="training_pics/default.png", upload_to='diet_pics')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    number = models.IntegerField(null=True)


    def get_absolute_url(self):
        return reverse("training:detail", args=[self.pk])


    def __str__(self):
        return str(self.id) + ' - ' + self.name

class TrainingReview(models.Model):
    context = models.TextField(max_length=1000)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(auto_now=True)
    object = models.ForeignKey(Training, on_delete=models.CASCADE)
    rating = models.FloatField(default=0)
    
    def __str__(self):
        return str(self.object) + ' - ' + str(self.author)

training/forms.py
from django import forms
from .models import TrainingReview

class ReviewForm(forms.ModelForm):

    class Meta:
        model = TrainingReview
        fields = ['context', 'rating']
        

training/views.py
from .models import Training, TrainingReview
from django.shortcuts import redirect, render
from django.contrib import messages
from .forms import ReviewForm
from django.core.paginator import Paginator


def indexView(request): 
    p = Paginator(Training.objects.all().order_by('-date'), 6)
    page = request.GET.get('page')
    trainings = p.get_page(page)
    for training in trainings:
        training.cut_context = training.context[0:200]
    context = {
        'trainings': trainings,
    }
    return render(request, 'training/index.html', context)


def detailView(request, training_id):
    reviews = TrainingReview.objects.filter(object__id=training_id)
    training = Training.objects.get(id=training_id)
    context = {
        'reviews': reviews,
        'training': training,
    }
    return render(request, 'training/detail.html', context)


def submit_review(request, training_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = TrainingReview.objects.get(author__id=request.user.profile.id, object__id=training_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        except TrainingReview.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = TrainingReview()
                data.context = form.cleaned_data['context']
                data.rating = form.cleaned_data['rating']
                data.object_id = training_id
                data.author = request.user.profile
                data.save()
                messages.success(request, 'Thank you! Your review has been submitted.')
                return redirect(url)

training/templates/training/detail.html
{% extends 'home/base.html' %}

{% block head %}
    {% load static %}
    <link href="{% static 'training/style_detail.css' %}" rel="stylesheet" >
{% endblock %}

{% block body %}
<div class="padding-top"></div>
<div class="container-fluid">
    <div class="col">
        <div class="row border-bottom">
            <div class="col-4 training-image">
                <div class="row justify-content-center border-right"><img class="picture" src="{{ training.image.url }}"></div>
            </div>
            <div class="col-8 training-info">
                <div class="row">
                    <h3>{{ training.name }}</h3>
                </div>
                <div class="row">
                    <img
                        src="{{ training.author.profile.image.url }}"
                        class="rounded-circle"
                        height="25"
                        alt="Black and White Portrait of a Man"
                        loading="lazy"
                        /> &nbsp; &nbsp;<a href="{{training.author.profile.get_absolute_url}}">{{ training.author.username }}</a>
                </div>
                <div class="row">
                    <p>{{training.date}}</p>
                </div>
                
            </div>
        </div>
        <div class="row training-context border-bottom">
            <div class="col">
                <div class="row">
                    <h1>Description:</h1>
                </div>
                <div class="row">
                    <p>{{training.context}}</p>
                </div>
            </div>
        </div>
        {% if not reviews %}
            <div class="row justify-content-center" style="padding:20px;padding-bottom:0;"><h3> No reviews yet. You can add yours first now!!</h3></div>
        {% else %}
            {% for review in reviews %}
            <div class="row reviews border-bottom">
                <div class="col">
                    <div class="row contex-image">
                        <img
                            src="{{ review.author.image.url }}"
                            class="rounded-circle"
                            height="25"
                            alt="Black and White Portrait of a Man"
                            loading="lazy"
                        /> &nbsp;&nbsp;<p>{{ review.author.user.username }}</p>  &nbsp; <span>
                            <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                        </span>
                    </div>
                    <div class="row contex">
                        <p>{{review.context}}</p>
                    </div>
                    <div class="row contex-stats">
                        <p>{{review.date}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% endif %}
        <div class="row justify-content-center" style="padding-top:40px;padding-bottom:40px;">
            <form action="{% url 'training:submit_review' training.id %}" method="POST">
                {% csrf_token %}
                <textarea name="context" cols="50" class="form-control review" rows="3" maxlength="1000" required="" id="id_context" required placeholder="Write your opinion here!!"></textarea>
                <div class="rate">
                    <input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10" title="5"></label>
                    <input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
                    <input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
                    <input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
                    <input type="radio" name="rating" id="rating6" value="3"  /><label for="rating6" title="3"></label>
                    <input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
                    <input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
                    <input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
                    <input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
                    <input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
                </div>
                {% if user.is_authenticated %}
                    <input type="submit" value="Submit Review" class="comment-like float-right">
                {% else %}
                    <p>You must be logged in to post a review. <span><a href="{% url 'login:login' %}">Login now</a></span></p>
                {% endif %}
            </form>
        </div>
    </div>
</div>
<div class="padding-bottom"></div>
{% endblock %}

training/templates/training/index.html
{% extends 'home/base.html' %}

{% block head %}
    {% load static %}
    <link href="{% static 'training/style.css' %}" rel="stylesheet" >
{% endblock %}
{% block body %}
<div class="padding-top"></div>
<div class="container-fluid">
    <div class="row justify-content-center">
    {% for training in trainings %}
        <div class="col-lg-3 col-12 training-card">
            <div class="row training-image">
                <img class="picture" src="{{ training.image.url }}">
                <div class="layer">
                    <p>{{ training.cut_context }}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-3 profile-image">
                    <div class="row justify-content-center"><img class="profile-picture rounded-circle" src="{{ training.author.profile.image.url }}"></div>
                </div>
                <div class="col-9">
                    <div class="row training-title">
                        <h3><a href="{% url 'training:detail' training.id %}">{{ training.name }}</a></h3>
                    </div>
                    <div class="row training-author">
                        <a href="{{ training.author.profile.get_absolute_url }}">{{ training.author }}</a>
                    </div>
                    <div class="row training-date">
                        <p>{{ training.date }}</p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
     <!-- PAGINATOR -->
    <div class="row justify-content-center">
        <nav aria-label="page-navigation">
            <ul class="pagination justify-content-center">
            {% if trainings.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1"><span aria-hidden="true">&laquo;</span></a></li>
                <li class="page-item"><a class="page-link" href="?page={{ trainings.previous_page_number }}"><span aria-hidden="true">&lsaquo;</span></a></li>
            {% endif %}
            
            {% for i in trainings.paginator.page_range %}
                <li class="{% if trainings.number == i %}active {% endif %}page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
            {% endfor %}

            {% if trainings.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ trainings.next_page_number }}"><span aria-hidden="true">&rsaquo;</span></a></li>
                <li class="page-item"><a class="page-link" href="?page={{ trainings.paginator.num_pages }}"><span aria-hidden="true">&raquo;</span></a></li>
            {% endif %}
            </ul>
        </nav>
    </div>
</div>
<div class="padding-bottom"></div>
{% endblock %}